# Generated by Django 5.0.3 on 2024-06-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuejasUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quejau',
            name='asunto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
