# Generated by Django 5.0.3 on 2024-05-30 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuejasUsuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoPrensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadAfectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Via',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('queja_id', models.IntegerField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(auto_created=True, default=1, editable=False)),
                ('nombre_apellidos', models.CharField(max_length=50)),
                ('fechaR', models.DateField()),
                ('fechaT', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('orden', models.IntegerField(default=0)),
                ('asunto', models.CharField(default='', max_length=50)),
                ('argumento', models.TextField(blank=True, max_length=10000)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('no_procedece', models.BooleanField(default=False)),
                ('casoPrensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionQuejasAPP.casoprensa')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionQuejasAPP.clasificacion')),
                ('entidadAfectada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionQuejasAPP.entidadafectada')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionQuejasAPP.modalidad')),
                ('procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionQuejasAPP.procedencia')),
                ('queja_u', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queja_us', to='QuejasUsuarios.quejau')),
                ('usuario_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_queja_created', to=settings.AUTH_USER_MODEL)),
                ('usuario_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_queja_updated', to=settings.AUTH_USER_MODEL)),
                ('via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionQuejasAPP.via')),
            ],
            options={
                'verbose_name': 'queja',
                'verbose_name_plural': 'quejas',
            },
        ),
        migrations.CreateModel(
            name='DocumentoQF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('queja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='GestionQuejasAPP.queja')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisQueja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis', models.TextField()),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('queja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='GestionQuejasAPP.queja')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=10000)),
                ('entrega', models.BooleanField(default=False)),
                ('fechaE', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionQuejasAPP.conclusion')),
                ('numero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta', to='GestionQuejasAPP.queja')),
                ('usuario_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_respuesta_created', to=settings.AUTH_USER_MODEL)),
                ('usuario_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_respuesta_updated', to=settings.AUTH_USER_MODEL)),
                ('satisfaccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionQuejasAPP.satisfaccion')),
            ],
            options={
                'verbose_name': 'respuesta',
                'verbose_name_plural': 'respuestas',
            },
        ),
        migrations.CreateModel(
            name='DocumentoR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='GestionQuejasAPP.respuesta')),
            ],
        ),
    ]
